const cards=[
{id:'card_001',title:'加班的狗',image:'assets/cards/card_001.svg',timer:90,criteria:['狗的脖子上系着领带','咖啡杯上有一个爱心','狗戴着圆框眼镜','墙上有飞镖盘','桌上有一根骨头','画面里有台灯','狗的一只耳朵折下来','飞镖盘上插着两根飞镖','办公桌有四个抽屉','咖啡热气至少有三条波浪线']},
{id:'card_002',title:'月球便利店',image:'assets/cards/card_002.svg',timer:90,criteria:['便利店招牌上有月亮','宇航员手里拿着购物篮','货架上有一瓶汽水','门口有一只猫','地面有倒影','收银台有算盘','月球表面有环形山','画面里有自动门','宇航员穿着靴子','天空中有三颗星星']},
{id:'card_003',title:'雨中的爵士乐队',image:'assets/cards/card_003.svg',timer:90,criteria:['乐手戴着礼帽','至少有一把萨克斯','地面有三把伞','鼓面上有闪电图案','舞台上有麦克风','雨线是斜着的','观众席有一只红鞋','贝斯手穿条纹袜','背景有路灯','水洼里有音符倒影']},
{id:'card_004',title:'海盗的生日会',image:'assets/cards/card_004.svg',timer:90,criteria:['海盗戴着眼罩','桌上有生日蛋糕','蛋糕上有五根蜡烛','墙上挂着藏宝图','有一只鹦鹉','桌边有木桶','窗外能看到大海','海盗穿着条纹衫','地上有一枚金币','旗子上有骷髅图案']},
{id:'card_005',title:'森林里的茶会',image:'assets/cards/card_005.svg',timer:90,criteria:['树桩上有茶壶','至少有两只蘑菇','兔子戴着蝴蝶结','桌布有格子纹','树上挂着风铃','茶杯冒着热气','有一只刺猬','背景有一条小溪','地上有三片落叶','太阳躲在云后面']}];
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="fullscreen.css">');
cards.forEach(card=>{card.image=card.image.replace(/\.svg$/i,'.webp')});
const $=s=>document.querySelector(s);let state={card:null,seconds:90,selectedTime:90,running:false,timeLocked:false,criterion:0,score:0,interval:null,endTime:null,pauseRemainingTime:90,ended:false};
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#screen-'+name).classList.add('active');$('#phase-label').textContent={home:'准备开局',rules:'玩法说明',prepare:'抽取画卡',draw:'描述与作画',score:'评分揭晓',result:'本轮结算'}[name]||''}
function goHome(){stopTimer();state.running=false;state.endTime=null;if($('#fullscreen-viewer'))$('#fullscreen-viewer').classList.add('hidden');show('home')}
function pick(){stopTimer();state.card=cards[Math.floor(Math.random()*cards.length)];state.selectedTime=state.card.timer;state.seconds=state.selectedTime;state.pauseRemainingTime=state.selectedTime;state.criterion=0;state.score=0;state.running=false;state.timeLocked=false;state.endTime=null;state.ended=false;$('#card-title').textContent=state.card.title;$('#card-image').src=state.card.image;$('#score-image').src=state.card.image;renderTimer();renderTimeSettings();$('#art-cover').classList.remove('hidden');$('#to-score').classList.add('hidden');$('#timer-toggle').textContent='开始';show('draw')}
function renderTimer(){const m=String(Math.floor(state.seconds/60)).padStart(2,'0'),s=String(state.seconds%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`;$('#timer').classList.toggle('danger',state.seconds<=10)}
function renderTimeSettings(){const locked=state.timeLocked||state.running||state.ended;$('#time-settings').classList.toggle('locked',locked);document.querySelectorAll('.time-preset[data-time]').forEach(button=>button.classList.toggle('selected',Number(button.dataset.time)===state.selectedTime));$('#custom-minutes').value=Math.floor(state.selectedTime/60);$('#custom-seconds').value=state.selectedTime%60}
function setTime(seconds){if(state.timeLocked||state.running||state.ended)return;const safe=Math.max(1,Math.min(5999,Math.round(seconds)));state.selectedTime=safe;state.seconds=safe;state.pauseRemainingTime=safe;renderTimer();renderTimeSettings()}
function applyCustomTime(){const minutes=Math.max(0,Math.min(99,Number($('#custom-minutes').value)||0));const seconds=Math.max(0,Math.min(59,Number($('#custom-seconds').value)||0));setTime(minutes*60+seconds)}
function stopTimer(){if(state.interval!==null){clearInterval(state.interval);state.interval=null}}
function finishTimer(){if(state.ended)return;state.ended=true;state.seconds=0;state.pauseRemainingTime=0;state.running=false;stopTimer();renderTimer();$('#timer-toggle').textContent='时间到';$('#art-cover').classList.remove('hidden');$('#to-score').classList.remove('hidden');beep()}
function refreshTimer(){if(!state.running||state.endTime===null)return;const remainingMs=state.endTime-Date.now();if(remainingMs<=0){finishTimer();return}state.seconds=Math.max(0,Math.ceil(remainingMs/1000));state.pauseRemainingTime=state.seconds;renderTimer()}
function toggleTimer(){if(state.ended||!state.card)return;if(state.running){refreshTimer();if(state.ended)return;state.pauseRemainingTime=state.seconds;state.running=false;state.endTime=null;stopTimer();$('#timer-toggle').textContent='继续';return}if(state.pauseRemainingTime<=0)return;state.timeLocked=true;state.endTime=Date.now()+state.pauseRemainingTime*1000;state.running=true;$('#timer-toggle').textContent='暂停';renderTimeSettings();$('#art-cover').classList.add('hidden');refreshTimer();if(state.running)state.interval=setInterval(refreshTimer,100)}
function beep(){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=520;g.gain.value=.08;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.16)}catch(e){}}
function resetTimer(){if(!state.card)return;stopTimer();state.seconds=state.selectedTime;state.pauseRemainingTime=state.selectedTime;state.running=false;state.timeLocked=false;state.endTime=null;state.ended=false;$('#timer-toggle').textContent='开始';$('#art-cover').classList.remove('hidden');renderTimer();renderTimeSettings()}
function setupFullscreen(){const artCard=$('.art-card');if(!artCard||$('#fullscreen-viewer'))return;const open=document.createElement('button');open.className='fullscreen-open';open.dataset.action='fullscreen-open';open.textContent='全屏查看';open.setAttribute('aria-label','全屏查看画卡');artCard.append(open);const viewer=document.createElement('div');viewer.id='fullscreen-viewer';viewer.className='fullscreen-viewer hidden';viewer.innerHTML='<button class="fullscreen-close" data-action="fullscreen-close" aria-label="关闭全屏">×</button><img id="fullscreen-image" alt="放大查看画卡">';document.body.append(viewer);let scale=1,x=0,y=0,startX=0,startY=0,pinchStart=0;const image=$('#fullscreen-image');function render(){image.style.transform=`translate3d(${x}px,${y}px,0) scale(${scale})`}function openViewer(){image.src=$('#card-image').src;scale=1;x=0;y=0;render();viewer.classList.remove('hidden')}function closeViewer(){viewer.classList.add('hidden')}openViewer.close=closeViewer;viewer.addEventListener('wheel',e=>{e.preventDefault();scale=Math.min(5,Math.max(1,scale+(e.deltaY<0?.25:-.25)));render()},{passive:false});viewer.addEventListener('pointerdown',e=>{if(e.target===image||e.target===viewer){viewer.setPointerCapture(e.pointerId);startX=e.clientX-x;startY=e.clientY-y}});viewer.addEventListener('pointermove',e=>{if(viewer.hasPointerCapture(e.pointerId)){x=e.clientX-startX;y=e.clientY-startY;render()}});viewer.addEventListener('pointerup',e=>{if(viewer.hasPointerCapture(e.pointerId))viewer.releasePointerCapture(e.pointerId)});viewer.addEventListener('touchstart',e=>{if(e.touches.length===2)pinchStart=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)},{passive:true});viewer.addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();const distance=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);scale=Math.min(5,Math.max(1,scale*(distance/pinchStart)));pinchStart=distance;render()}},{passive:false})}
function startScore(){clearInterval(state.interval);state.criterion=0;state.score=0;$('#score-number').textContent='0';renderCriterion();show('score')}
function renderCriterion(){const i=state.criterion;$('#criterion-count').textContent=`第 ${i+1} 条 / 10`;$('#criterion-text').textContent=state.card.criteria[i]}
function answer(hit){if(hit)state.score++;state.criterion++;if(state.criterion>=10){$('#final-score').textContent=state.score;$('#result-copy').textContent=state.score>=7?'真迹级别！艺术总监慧眼如炬。':state.score>=4?'不错的观察力，下一幅继续挑战。':'赝品画师成功混入，下一轮扳回一城。';show('result')}else renderCriterion()}
setupFullscreen();document.addEventListener('click',e=>{const a=e.target.dataset.action;if(a==='time-preset')setTime(Number(e.target.dataset.time));if(a==='custom-time'){document.querySelector('.custom-time').scrollIntoView({behavior:'smooth',block:'nearest'});$('#custom-minutes').focus()}if(a==='apply-custom')applyCustomTime();if(a==='fullscreen-open')$('#fullscreen-viewer').classList.remove('hidden'),$('#fullscreen-image').src=$('#card-image').src;if(a==='fullscreen-close')$('#fullscreen-viewer').classList.add('hidden');if(a==='start'||a==='again')show('prepare');if(a==='home')goHome();if(a==='rules')show('rules');if(a==='reveal-card')pick();if(a==='toggle-timer')toggleTimer();if(a==='reset-timer')resetTimer();if(a==='score')startScore();if(a==='hit')answer(true);if(a==='miss')answer(false)});
